service:
  name: dog-finder-db

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'us-east-1'}
  environment:
    DB_NAME: dog-finder-db-${self:provider.stage}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-local}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"


custom:
  dynamodb:
    start:
      migrate: true
      seed: true
    stages:
      - dev
      - staging
    seed:
      local:
        sources:
          - table: ${self:provider.environment.DB_NAME}
            sources: [./seeds/notices.json]
  endpoints:
    dynamodb-local: 'http://localhost:8000'

plugins:
  - serverless-dynamodb-local

resources:
  Resources:
    DynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "entry"
            AttributeType: "S"
          - AttributeName: "type"
            AttributeType: "S"
          - AttributeName: "createdAt"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "entry"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: "type-createdAt-index"
            KeySchema:
              - AttributeName: "type"
                KeyType: "HASH"
              - AttributeName: "createdAt"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DB_NAME}
