service:
  name: api-ts

provider:
  name: aws
  runtime: nodejs12.x
  frameworkVersion: '1.75.1'
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  tracing:
    lambda: true
  environment:
    DEBUG: '*'
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DB_NAME: dog-finder-ts
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-local}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-iam-roles-per-function:
    defaultInherit: true # Each function will inherit the service level roles too.
  prune: # automatically prune old lambda versions
    automatic: true
    number: 3
  dynamodb:
    start:
      migrate: true
      seed: true
    stages:
      - local
    seed:
      local:
        sources:
          - table: ${self:provider.environment.DB_NAME}
            sources: [./seeds/notices.json]
  endpoints:
    dynamodb-local: 'http://localhost:8000'

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-dynamodb-local

resources:
  Resources:
    DynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "type"
            AttributeType: "S"
          - AttributeName: "createdAt"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "type"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: "type-createdAt-index"
            KeySchema:
              - AttributeName: "type"
                KeyType: "HASH"
              - AttributeName: "createdAt"
                KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
                
        TableName: ${self:provider.environment.DB_NAME}

functions:
  foundDogCreate:
    handler: src/handlers/foundDog.create
    events:
      - http:
          method: post
          path: found-dog
  foundDogDelete:
    handler: src/handlers/foundDog.del
    events:
      - http:
          method: delete
          path: found-dog/{id}
  foundDogEdit:
    handler: src/handlers/foundDog.edit
    events:
      - http:
          method: put
          path: found-dog/{id}
  foundDogDetail:
    handler: src/handlers/foundDog.detail
    events:
      - http:
          method: get
          path: found-dog/{id}
  foundDogList:
    handler: src/handlers/foundDog.list
    events:
      - http:
          method: get
          path: found-dog
  lostDogCreate:
    handler: src/handlers/lostDog.create
    events:
      - http:
          method: post
          path: lost-dog
  lostDogDelete:
    handler: src/handlers/lostDog.del
    events:
      - http:
          method: delete
          path: lost-dog/{id}
  lostDogEdit:
    handler: src/handlers/lostDog.edit
    events:
      - http:
          method: put
          path: lost-dog/{id}
  lostDogDetail:
    handler: src/handlers/lostDog.detail
    events:
      - http:
          method: get
          path: lost-dog/{id}
  lostDogList:
    handler: src/handlers/lostDog.list
    events:
      - http:
          method: get
          path: lost-dog
  imageUpload:
    handler: src/handlers/images.upload
    events:
      - http:
          path: upload
          method: get
