import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('dog-finder-ts')
export class MyDomainObject {
    @autoGeneratedHashKey()
    id: string;

    @rangeKey()
    createdAt: Date;

    @attribute()
    name: string;

    @attribute()
    completed?: boolean;
}
